// <auto-generated />
using System;
using System.Collections.Generic;
using Maliev.PredictionService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Maliev.PredictionService.Infrastructure.Migrations
{
    [DbContext(typeof(PredictionDbContext))]
    [Migration("20260214140917_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Maliev.PredictionService.Domain.Entities.MLModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Algorithm")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("DeploymentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb");

                    b.Property<string>("ModelType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TrainingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("TrainingJobId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "ModelVersion", "Maliev.PredictionService.Domain.Entities.MLModel.ModelVersion#ModelVersion", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Major")
                                .HasColumnType("integer")
                                .HasColumnName("version_major");

                            b1.Property<int>("Minor")
                                .HasColumnType("integer")
                                .HasColumnName("version_minor");

                            b1.Property<int>("Patch")
                                .HasColumnType("integer")
                                .HasColumnName("version_patch");
                        });

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_ml_models_created_at");

                    b.HasIndex("TrainingJobId")
                        .IsUnique();

                    b.HasIndex("ModelType", "Status")
                        .HasDatabaseName("ix_ml_models_type_status");

                    b.ToTable("ml_models", "ml_models");
                });

            modelBuilder.Entity("Maliev.PredictionService.Domain.Entities.PredictionAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActualOutcome")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("ActualOutcomeReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CacheStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("InputFeatures")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ModelType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("OutputPrediction")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ResponseTimeMs")
                        .HasColumnType("integer");

                    b.Property<string>("TenantId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ActualOutcomeReceivedAt")
                        .HasDatabaseName("ix_prediction_audit_logs_actual_outcome")
                        .HasFilter("actual_outcome_received_at IS NOT NULL");

                    b.HasIndex("RequestId")
                        .HasDatabaseName("ix_prediction_audit_logs_request_id");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("ix_prediction_audit_logs_timestamp");

                    b.HasIndex("ModelType", "Timestamp")
                        .HasDatabaseName("ix_prediction_audit_logs_type_timestamp");

                    b.HasIndex("UserId", "Timestamp")
                        .HasDatabaseName("ix_prediction_audit_logs_user_timestamp");

                    b.ToTable("prediction_audit_logs", "audit");
                });

            modelBuilder.Entity("Maliev.PredictionService.Domain.Entities.TrainingDataset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DataQualityMetrics")
                        .HasColumnType("jsonb");

                    b.Property<string>("DatasetHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("DateRangeEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateRangeStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FeatureColumns")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("FilePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ModelType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RecordCount")
                        .HasColumnType("integer");

                    b.Property<string>("TargetColumn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("TrainingJobId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_training_datasets_created_at");

                    b.HasIndex("DatasetHash")
                        .HasDatabaseName("ix_training_datasets_hash");

                    b.HasIndex("ModelType")
                        .HasDatabaseName("ix_training_datasets_model_type");

                    b.HasIndex("TrainingJobId")
                        .IsUnique();

                    b.ToTable("training_datasets", "training");
                });

            modelBuilder.Entity("Maliev.PredictionService.Domain.Entities.TrainingJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Hyperparameters")
                        .HasColumnType("jsonb");

                    b.Property<string>("Logs")
                        .HasColumnType("text");

                    b.Property<Guid?>("ModelId")
                        .HasColumnType("uuid");

                    b.Property<string>("ModelType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TrainingDatasetId")
                        .HasColumnType("uuid");

                    b.Property<string>("TriggeredBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TriggeredByUserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ValidationResults")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("ModelType")
                        .HasDatabaseName("ix_training_jobs_model_type");

                    b.HasIndex("StartTime")
                        .HasDatabaseName("ix_training_jobs_start_time");

                    b.HasIndex("Status", "StartTime")
                        .HasDatabaseName("ix_training_jobs_status_start");

                    b.ToTable("training_jobs", "training");
                });

            modelBuilder.Entity("Maliev.PredictionService.Domain.Entities.MLModel", b =>
                {
                    b.HasOne("Maliev.PredictionService.Domain.Entities.TrainingJob", "TrainingJob")
                        .WithOne("Model")
                        .HasForeignKey("Maliev.PredictionService.Domain.Entities.MLModel", "TrainingJobId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("Maliev.PredictionService.Domain.ValueObjects.PerformanceMetrics", "PerformanceMetrics", b1 =>
                        {
                            b1.Property<Guid>("MLModelId");

                            b1.Property<double?>("AUC");

                            b1.Property<double?>("F1Score");

                            b1.Property<double?>("MAE");

                            b1.Property<double?>("MAPE");

                            b1.Property<double?>("Precision");

                            b1.Property<double?>("RMSE");

                            b1.Property<double?>("RSquared");

                            b1.Property<double?>("Recall");

                            b1.HasKey("MLModelId");

                            b1.ToTable("ml_models", "ml_models");

                            b1
                                .ToJson("PerformanceMetrics")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("MLModelId");
                        });

                    b.Navigation("PerformanceMetrics");

                    b.Navigation("TrainingJob");
                });

            modelBuilder.Entity("Maliev.PredictionService.Domain.Entities.TrainingDataset", b =>
                {
                    b.HasOne("Maliev.PredictionService.Domain.Entities.TrainingJob", "TrainingJob")
                        .WithOne("TrainingDataset")
                        .HasForeignKey("Maliev.PredictionService.Domain.Entities.TrainingDataset", "TrainingJobId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("TrainingJob");
                });

            modelBuilder.Entity("Maliev.PredictionService.Domain.Entities.TrainingJob", b =>
                {
                    b.OwnsOne("Maliev.PredictionService.Domain.ValueObjects.PerformanceMetrics", "PerformanceMetrics", b1 =>
                        {
                            b1.Property<Guid>("TrainingJobId");

                            b1.Property<double?>("AUC");

                            b1.Property<double?>("F1Score");

                            b1.Property<double?>("MAE");

                            b1.Property<double?>("MAPE");

                            b1.Property<double?>("Precision");

                            b1.Property<double?>("RMSE");

                            b1.Property<double?>("RSquared");

                            b1.Property<double?>("Recall");

                            b1.HasKey("TrainingJobId");

                            b1.ToTable("training_jobs", "training");

                            b1
                                .ToJson("PerformanceMetrics")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("TrainingJobId");
                        });

                    b.Navigation("PerformanceMetrics");
                });

            modelBuilder.Entity("Maliev.PredictionService.Domain.Entities.TrainingJob", b =>
                {
                    b.Navigation("Model");

                    b.Navigation("TrainingDataset");
                });
#pragma warning restore 612, 618
        }
    }
}
