// <auto-generated />
using System;
using System.Collections.Generic;
using Maliev.PredictionService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Maliev.PredictionService.Infrastructure.Migrations
{
    [DbContext(typeof(PredictionDbContext))]
    partial class PredictionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Maliev.PredictionService.Domain.Entities.MLModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Algorithm")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("algorithm");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeploymentDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deployment_date");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_path");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("ModelType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model_type");

                    b.Property<string>("PerformanceMetrics")
                        .HasColumnType("jsonb")
                        .HasColumnName("performance_metrics");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("TrainingDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("training_date");

                    b.Property<Guid?>("TrainingJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("training_job_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "ModelVersion", "Maliev.PredictionService.Domain.Entities.MLModel.ModelVersion#ModelVersion", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Major")
                                .HasColumnType("integer")
                                .HasColumnName("version_major");

                            b1.Property<int>("Minor")
                                .HasColumnType("integer")
                                .HasColumnName("version_minor");

                            b1.Property<int>("Patch")
                                .HasColumnType("integer")
                                .HasColumnName("version_patch");
                        });

                    b.HasKey("Id")
                        .HasName("p_k_ml_models");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_ml_models_created_at");

                    b.HasIndex("TrainingJobId")
                        .IsUnique()
                        .HasDatabaseName("i_x_ml_models_training_job_id");

                    b.HasIndex("ModelType", "Status")
                        .HasDatabaseName("ix_ml_models_type_status");

                    b.ToTable("ml_models", "ml_models");
                });

            modelBuilder.Entity("Maliev.PredictionService.Domain.Entities.PredictionAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActualOutcome")
                        .HasColumnType("jsonb")
                        .HasColumnName("actual_outcome");

                    b.Property<DateTime?>("ActualOutcomeReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actual_outcome_received_at");

                    b.Property<string>("CacheStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cache_status");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("error_message");

                    b.Property<string>("InputFeatures")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("input_features");

                    b.Property<string>("ModelType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model_type");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("model_version");

                    b.Property<string>("OutputPrediction")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("output_prediction");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("request_id");

                    b.Property<int>("ResponseTimeMs")
                        .HasColumnType("integer")
                        .HasColumnName("response_time_ms");

                    b.Property<string>("TenantId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_prediction_audit_logs");

                    b.HasIndex("ActualOutcomeReceivedAt")
                        .HasDatabaseName("ix_prediction_audit_logs_actual_outcome")
                        .HasFilter("actual_outcome_received_at IS NOT NULL");

                    b.HasIndex("RequestId")
                        .HasDatabaseName("ix_prediction_audit_logs_request_id");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("ix_prediction_audit_logs_timestamp");

                    b.HasIndex("ModelType", "Timestamp")
                        .HasDatabaseName("ix_prediction_audit_logs_type_timestamp");

                    b.HasIndex("UserId", "Timestamp")
                        .HasDatabaseName("ix_prediction_audit_logs_user_timestamp");

                    b.ToTable("prediction_audit_logs", "audit");
                });

            modelBuilder.Entity("Maliev.PredictionService.Domain.Entities.TrainingDataset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<string>("DataQualityMetrics")
                        .HasColumnType("jsonb")
                        .HasColumnName("data_quality_metrics");

                    b.Property<string>("DatasetHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("dataset_hash");

                    b.Property<DateTime>("DateRangeEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_range_end");

                    b.Property<DateTime>("DateRangeStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_range_start");

                    b.Property<string>("FeatureColumns")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("feature_columns");

                    b.Property<string>("FilePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_path");

                    b.Property<string>("ModelType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model_type");

                    b.Property<int>("RecordCount")
                        .HasColumnType("integer")
                        .HasColumnName("record_count");

                    b.Property<string>("TargetColumn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("target_column");

                    b.Property<Guid?>("TrainingJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("training_job_id");

                    b.HasKey("Id")
                        .HasName("p_k_training_datasets");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_training_datasets_created_at");

                    b.HasIndex("DatasetHash")
                        .HasDatabaseName("ix_training_datasets_hash");

                    b.HasIndex("ModelType")
                        .HasDatabaseName("ix_training_datasets_model_type");

                    b.HasIndex("TrainingJobId")
                        .IsUnique()
                        .HasDatabaseName("i_x_training_datasets_training_job_id");

                    b.ToTable("training_datasets", "training");
                });

            modelBuilder.Entity("Maliev.PredictionService.Domain.Entities.TrainingJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message");

                    b.Property<string>("Hyperparameters")
                        .HasColumnType("jsonb")
                        .HasColumnName("hyperparameters");

                    b.Property<string>("Logs")
                        .HasColumnType("text")
                        .HasColumnName("logs");

                    b.Property<Guid?>("ModelId")
                        .HasColumnType("uuid")
                        .HasColumnName("model_id");

                    b.Property<string>("ModelType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model_type");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid?>("TrainingDatasetId")
                        .HasColumnType("uuid")
                        .HasColumnName("training_dataset_id");

                    b.Property<string>("TriggeredBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("triggered_by");

                    b.Property<string>("TriggeredByUserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("triggered_by_user_id");

                    b.Property<string>("ValidationResults")
                        .HasColumnType("jsonb")
                        .HasColumnName("validation_results");

                    b.HasKey("Id")
                        .HasName("p_k_training_jobs");

                    b.HasIndex("ModelType")
                        .HasDatabaseName("ix_training_jobs_model_type");

                    b.HasIndex("StartTime")
                        .HasDatabaseName("ix_training_jobs_start_time");

                    b.HasIndex("Status", "StartTime")
                        .HasDatabaseName("ix_training_jobs_status_start");

                    b.ToTable("training_jobs", "training");
                });

            modelBuilder.Entity("Maliev.PredictionService.Domain.Entities.MLModel", b =>
                {
                    b.HasOne("Maliev.PredictionService.Domain.Entities.TrainingJob", "TrainingJob")
                        .WithOne("Model")
                        .HasForeignKey("Maliev.PredictionService.Domain.Entities.MLModel", "TrainingJobId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("f_k_ml_models_training_jobs_training_job_id");

                    b.Navigation("TrainingJob");
                });

            modelBuilder.Entity("Maliev.PredictionService.Domain.Entities.TrainingDataset", b =>
                {
                    b.HasOne("Maliev.PredictionService.Domain.Entities.TrainingJob", "TrainingJob")
                        .WithOne("TrainingDataset")
                        .HasForeignKey("Maliev.PredictionService.Domain.Entities.TrainingDataset", "TrainingJobId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("f_k_training_datasets_training_jobs_training_job_id");

                    b.Navigation("TrainingJob");
                });

            modelBuilder.Entity("Maliev.PredictionService.Domain.Entities.TrainingJob", b =>
                {
                    b.OwnsOne("Maliev.PredictionService.Domain.ValueObjects.PerformanceMetrics", "PerformanceMetrics", b1 =>
                        {
                            b1.Property<Guid>("TrainingJobId");

                            b1.Property<double?>("AUC");

                            b1.Property<double?>("F1Score");

                            b1.Property<double?>("MAE");

                            b1.Property<double?>("MAPE");

                            b1.Property<double?>("Precision");

                            b1.Property<double?>("RMSE");

                            b1.Property<double?>("RSquared");

                            b1.Property<double?>("Recall");

                            b1.HasKey("TrainingJobId");

                            b1.ToTable("training_jobs", "training");

                            b1
                                .ToJson("PerformanceMetrics")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("TrainingJobId");
                        });

                    b.Navigation("PerformanceMetrics");
                });

            modelBuilder.Entity("Maliev.PredictionService.Domain.Entities.TrainingJob", b =>
                {
                    b.Navigation("Model");

                    b.Navigation("TrainingDataset");
                });
#pragma warning restore 612, 618
        }
    }
}
